"""adicion imagen modelo post

Revision ID: 4867a1fc6e73
Revises: 4fa4b0475cbe
Create Date: 2022-06-18 16:52:57.850410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4867a1fc6e73'
down_revision = '4fa4b0475cbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image_name')
    # ### end Alembic commands ###
