"""adicion campo prueba

Revision ID: 5b22013f7b5f
Revises: a36fce66f74f
Create Date: 2022-06-16 10:50:42.275709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b22013f7b5f'
down_revision = 'a36fce66f74f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('prueba', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'prueba')
    # ### end Alembic commands ###
